version: '3'

services:
  discordbot: 
    container_name: cbg-discord-bot
    build: .
    volumes:
      - .:/usr/src/cbg-discord-bot/
      - /usr/src/cbg-discord-bot/node_modules
    command: npm run start
    ports:
      - "127.0.0.1:8080:8080"
    env_file: .env
    environment:
      NODE_ENV: production
    restart: always