version: '3'

services:
  discordbot: 
    container_name: cbg-discord-bot
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - .:/usr/src/cbg-discord-bot
      - /usr/src/node_modules
    ports:
      - "3030:3030"
    env_file: .env
    restart: always