version: '3'

services:
  discordbot: 
    container_name: cbg-discord-bot
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/cbg-discord-bot
    command: npm run start
    ports:
      - "3030:3030"
    env_file: .env
    environment:
      NODE_ENV: production
    restart: always